# Auto-generated by self-healing-agent
import pytest
from tests.fixtures.buggy_service import get_user_profile


def test_get_user_profile_missing_user_id():
    """Fails on unfixed code (KeyError), passes on fixed code."""
    result = get_user_profile({})
    assert result == {"id": "", "active": True}


def test_get_user_profile_with_user_id():
    """Regression guard — must still work when user_id is present."""
    result = get_user_profile({"user_id": "abc123"})
    assert result == {"id": "abc123", "active": True}
